# Generated by Django 5.1.5 on 2025-01-28 03:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='ImagePost',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='image_post',
        ),
    ]
